# Generated by Django 5.1.5 on 2025-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(default=None, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='carousels/images/', verbose_name='Display banner')),
                ('created_on', models.DateTimeField(default=None, verbose_name='Created on')),
                ('displayed_from', models.DateField(verbose_name='To be displayed from')),
                ('displayed_to', models.DateField(verbose_name='To be displayed till')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
