# Generated by Django 5.1.5 on 2025-02-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=15, verbose_name='First Name')),
                ('middle_name', models.TextField(max_length=15, verbose_name='Middle Name')),
                ('last_name', models.TextField(max_length=15, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mobile_number', models.IntegerField(verbose_name='Mobile Number')),
                ('shop_name', models.TextField(max_length=100, verbose_name='Diplay Name/Shop Name')),
                ('holiday_mode', models.BooleanField(default=False, verbose_name='Holiday Mode')),
                ('holiday_start', models.DateField(verbose_name='Holiday Starts from')),
                ('holiday_end', models.DateField(verbose_name='Holiday Ends on')),
                ('seller_type', models.TextField(max_length=50, verbose_name='Seller Type')),
                ('legal_name', models.TextField(max_length=100, verbose_name='Legal Name/ Business Owner Name')),
                ('business_address', models.TextField(max_length=100, verbose_name='Business Address')),
                ('business_city', models.TextField(verbose_name='City')),
                ('homepage', models.URLField(verbose_name='Seller Hompage')),
            ],
        ),
    ]
