# Generated by Django 5.1.5 on 2025-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasperhtml',
            name='units_sold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Units Sold'),
        ),
        migrations.AddField(
            model_name='productasperhtml',
            name='updated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Updated Price'),
        ),
    ]
