# Generated by Django 5.1.5 on 2025-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_productasperhtml_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Electronics'), (2, 'Clothes')], max_length=111, verbose_name='Category'),
        ),
    ]
