# Generated by Django 5.1.5 on 2025-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes')], max_length=111, verbose_name='Category'),
        ),
    ]
