# Generated by Django 5.1.5 on 2025-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Updated Price'),
        ),
    ]
