# Generated by Django 5.1.5 on 2025-02-19 10:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=254, verbose_name='Agency Name')),
                ('role', models.CharField(max_length=254, verbose_name='Role in Agency')),
                ('agency_email', models.EmailField(max_length=254, verbose_name='Agency Email Address')),
                ('agency_website', models.URLField(verbose_name='Website')),
                ('agency_address', models.TextField(verbose_name='Address')),
                ('region', models.CharField(max_length=111, verbose_name='Region of Operation')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='seller/documents', verbose_name='Upload Business Documents')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.CharField(max_length=121, verbose_name='Preferred Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('student_count', models.PositiveIntegerField(verbose_name='Number of Students Reqruited Annually')),
                ('focus_area', models.TextField(verbose_name='Focus Area')),
                ('success_metrics', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Success Metrics')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutions', models.CharField(choices=[(1, 'Universities'), (2, 'Colleges'), (3, 'Vocational School'), (4, 'Others')], max_length=50, verbose_name='Preferred Institution Types')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[(1, 'Career Counseling'), (2, 'Admission Applications'), (3, 'Visa Processing'), (4, 'Test Preparation')], max_length=50, verbose_name='Services Provided')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_reg_number', models.CharField(max_length=150, verbose_name='Business Registration Number')),
                ('certification', models.CharField(max_length=150, verbose_name='Certification Details')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='seller.country', verbose_name='')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_doc', to='seller.businessdoc', verbose_name='Upload Business Documents')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instiution', to='seller.institution', verbose_name='Preferred Institution Types')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=254, verbose_name='Password')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='seller.agency', verbose_name='agency Details')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='seller.experience', verbose_name='Experience and Performance Metics')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='seller.service', verbose_name='Services Provided'),
        ),
    ]
